SKILLS = [
    "python",
    "sql",
    "mysql",
    "postgresql",
    "excel",
    "power bi",
    "tableau",
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "scikit-learn",
    "machine learning",
    "deep learning",
    "statistics",
    "data analysis",
    "data visualization",
    "streamlit",
    "fastapi",
    "git",
    "github",
    "docker",
    "linux",
    "aws",
    "azure",
    "gcp",
    "tensorflow",
    "keras",
    "pytorch",
    "opencv",
    "html",
    "css",
    "javascript",
    "flask",
    "mongodb"
]